#ifndef LocalManifest_h
#define LocalManifest_h

#include <stdint.h>
#include "RoveCommManifest.h"

#define RC_FOREARM_FOURTHOCTET       128
#define RC_BICEP_FOURTHOCTET         129

//Forearm Currents
#define RC_ARMBOARD_FOREARM_MOTORCURRENTS_DATAID     	05+_TYPE_TELEMETRY+_ARMBOARD_BOARDNUMBER
#define RC_ARMBOARD_FOREARM_MOTORCURRENTS_DATATYPE   	uint8_t	//A-1
#define RC_ARMBOARD_FOREARM_MOTORCURRENTS_DATACOUNT  	4			//[M5][M6][M7][M8]
#define RC_ARMBOARD_FOREARM_MOTORCURRENTS_HEADER		  RC_ARMBOARD_FOREARM_MOTORCURRENTS_DATAID,RC_ARMBOARD_FOREARM_MOTORCURRENTS_DATACOUNT
#define	RC_ARMBOARD_FOREARM_MOTORCURRENTS_M5ENTRY		  0
#define	RC_ARMBOARD_FOREARM_MOTORCURRENTS_M6ENTRY		  1
#define	RC_ARMBOARD_FOREARM_MOTORCURRENTS_M5ENTRY		  2
#define	RC_ARMBOARD_FOREARM_MOTORCURRENTS_M6ENTRY		  3

//Forearm Currents
#define RC_ARMBOARD_BICEP_MOTORCURRENTS_DATAID     	06+_TYPE_TELEMETRY+_ARMBOARD_BOARDNUMBER
#define RC_ARMBOARD_BICEP_MOTORCURRENTS_DATATYPE   	uint8_t	//A-1
#define RC_ARMBOARD_BICEP_MOTORCURRENTS_DATACOUNT  	2			//[M1][M2][M3][M4]
#define RC_ARMBOARD_BICEP_MOTORCURRENTS_HEADER		  RC_ARMBOARD_BICEP_MOTORCURRENTS_DATAID,RC_ARMBOARD_BICEP_MOTORCURRENTS_DATACOUNT
#define	RC_ARMBOARD_BICEP_MOTORCURRENTS_M1ENTRY		  0
#define	RC_ARMBOARD_BICEP_MOTORCURRENTS_M2ENTRY		  1
#define	RC_ARMBOARD_BICEP_MOTORCURRENTS_M3ENTRY		  2
#define	RC_ARMBOARD_BICEP_MOTORCURRENTS_M4ENTRY		  3

//Forearm Motors
#define RC_ARMBOARD_FOREARM_DATAID     	8+_TYPE_COMMAND+_ARMBOARD_BOARDNUMBER
#define RC_ARMBOARD_FOREARM_DATATYPE   	int16_t	//[J5][J6][-1000, 1000] %-1
#define RC_ARMBOARD_FOREARM_DATACOUNT  	2
#define RC_ARMBOARD_FOREARM_HEADER		  RC_ARMBOARD_FOREARM_DATAID,RC_ARMBOARD_FOREARM_DATACOUNT
#define RC_ARMBOARD_FOREARM_J5ENTRY	    0
#define RC_ARMBOARD_FOREARM_J6ENTRY	    1

//Bicep Motors
#define RC_ARMBOARD_BICEP_DATAID     	9+_TYPE_COMMAND+_ARMBOARD_BOARDNUMBER
#define RC_ARMBOARD_BICEP_DATATYPE   	int16_t	//[J1][J2][J3][J4][-1000, 1000] %-1
#define RC_ARMBOARD_BICEP_DATACOUNT  	4
#define RC_ARMBOARD_BICEP_HEADER		  RC_ARMBOARD_BICEP_DATAID,RC_ARMBOARD_BICEP_DATACOUNT
#define RC_ARMBOARD_BICEP_J1ENTRY	    0
#define RC_ARMBOARD_BICEP_J2ENTRY	    1
#define RC_ARMBOARD_BICEP_J3ENTRY	    2
#define RC_ARMBOARD_BICEP_J4ENTRY	    3

//Bicep Motors
#define RC_ARMBOARD_GRIPPER_DATAID     	10+_TYPE_COMMAND+_ARMBOARD_BOARDNUMBER
#define RC_ARMBOARD_GRIPPER_DATATYPE   	int16_t	//[J1][J2][J3][J4][-1000, 1000] %-1
#define RC_ARMBOARD_GRIPPER_DATACOUNT  	2
#define RC_ARMBOARD_GRIPPER_HEADER		  RC_ARMBOARD_GRIPPER_DATAID,RC_ARMBOARD_GRIPPER_DATACOUNT
#define RC_ARMBOARD_GRIPPER_ENTRY	      0


#endif
